import { afterEach, describe, expect, it } from "vitest";
import { findEnvKeys, getEnvApiKey } from "../src/env-api-keys.ts";
import { mindshubProvider } from "../src/providers/mindshub.ts";

const originalMindshubApiKey = process.env.MINDSHUB_API_KEY;

afterEach(() => {
	if (originalMindshubApiKey === undefined) {
		delete process.env.MINDSHUB_API_KEY;
	} else {
		process.env.MINDSHUB_API_KEY = originalMindshubApiKey;
	}
});

// MindsHub isn't indexed by models.dev, so unlike most other providers its catalog is
// hand-maintained rather than generated by `scripts/generate-models.ts`. It's registered
// with `createProvider()` like any other static-catalog provider, so it's read directly
// off the provider instance here instead of through the generated `getModel()`/`getModels()`
// static catalog helpers in `../src/compat.ts` (which only cover generated providers).
function getModel(id: string) {
	const model = mindshubProvider()
		.getModels()
		.find((candidate) => candidate.id === id);
	if (!model) throw new Error(`Unknown MindsHub model: ${id}`);
	return model;
}

describe("MindsHub models", () => {
	it("registers the provider with the documented base URL and auth", () => {
		const provider = mindshubProvider();
		expect(provider.id).toBe("mindshub");
		expect(provider.baseUrl).toBe("https://api.mindshub.ai/v1");
		expect(provider.getModels().length).toBeGreaterThan(0);
	});

	it("registers sonnet via the OpenAI-compatible Chat Completions API", () => {
		const model = getModel("sonnet");

		expect(model).toBeDefined();
		expect(model.api).toBe("openai-completions");
		expect(model.provider).toBe("mindshub");
		expect(model.baseUrl).toBe("https://api.mindshub.ai/v1");
		expect(model.reasoning).toBe(true);
		expect(model.thinkingLevelMap).toEqual({ minimal: null, low: "low", medium: "medium", high: "high", max: "max" });
		expect(model.input).toEqual(["text", "image"]);
		expect(model.maxTokens).toBe(131072);
		expect(model.cost).toEqual({ input: 2.0, output: 10.0, cacheRead: 0.2, cacheWrite: 2.5 });
		expect(model.compat).toEqual({
			supportsDeveloperRole: false,
			supportsStore: false,
			supportsStrictMode: false,
			supportsLongCacheRetention: false,
			supportsReasoningEffort: true,
			maxTokensField: "max_completion_tokens",
			thinkingFormat: "openai",
		});
	});

	it("marks mindshub_air and kimi as reasoning without an adjustable effort ladder", () => {
		const air = getModel("mindshub_air");
		expect(air.reasoning).toBe(false);
		expect(air.thinkingLevelMap).toBeUndefined();

		const kimi = getModel("kimi");
		expect(kimi.reasoning).toBe(false);
		expect(kimi.thinkingLevelMap).toBeUndefined();
	});

	it("models DeepSeek's documented low/high/max ladder (no medium)", () => {
		const deepseek = getModel("deepseek");
		expect(deepseek.reasoning).toBe(true);
		expect(deepseek.thinkingLevelMap).toEqual({
			off: null,
			minimal: null,
			low: "low",
			medium: null,
			high: "high",
			max: "max",
		});
	});

	it("models gpt-mini's documented off-via-none reasoning support", () => {
		const gptMini = getModel("gpt-mini");
		expect(gptMini.reasoning).toBe(true);
		expect(gptMini.thinkingLevelMap).toEqual({ off: "none" });
	});

	it("enforces the documented 131,072 max_tokens ceiling across the catalog", () => {
		for (const modelId of ["mindshub_air", "sonnet", "opus", "gpt", "gemini", "kimi", "deepseek", "grok"]) {
			expect(getModel(modelId).maxTokens).toBe(131072);
		}
	});

	it("accepts image input on every model, matching MindsHub's chat-completions docs", () => {
		for (const modelId of ["mindshub_air", "sonnet", "gpt-nano", "gemini-flash", "muse-spark", "grok-4-5"]) {
			expect(getModel(modelId).input).toEqual(["text", "image"]);
		}
	});

	it("resolves MINDSHUB_API_KEY from the environment", () => {
		process.env.MINDSHUB_API_KEY = "test-mindshub-key";

		expect(findEnvKeys("mindshub")).toEqual(["MINDSHUB_API_KEY"]);
		expect(getEnvApiKey("mindshub")).toBe("test-mindshub-key");
	});
});
