# This file is auto-generated by scripts/generate-image-models.ts
# Do not edit manually - run 'npm run generate-image-models' to update
import json
import os
from typing import cast
from pi_mono.ai.types import ImagesModel

_dir = os.path.dirname(os.path.abspath(__file__))
_path = os.path.join(_dir, "image-models.generated.json")

with open(_path, "r", encoding="utf-8") as _f:
    IMAGE_MODELS = cast(dict[str, dict[str, ImagesModel]], json.load(_f))
