# This file is auto-generated by scripts/generate-models.ts
# Do not edit manually - run 'npm run generate-models' to update
import json
import os
from typing import cast
from pi_mono.ai.types import Model

_dir = os.path.dirname(os.path.abspath(__file__))
_path = os.path.join(_dir, "models.generated.json")

with open(_path, "r", encoding="utf-8") as _f:
    MODELS = cast(dict[str, dict[str, Model]], json.load(_f))
