"""Extension system for lifecycle events and custom tools."""

from pi_mono.coding_agent.core.extensions.loader import (
    collect_configured_extension_paths,
    create_extension_runtime,
    discover_and_load_extensions,
    discover_extensions_in_dir,
    load_extension_from_factory,
    load_extensions,
)
from pi_mono.coding_agent.core.extensions.runner import ExtensionRunner, emit_session_shutdown_event
from pi_mono.coding_agent.core.extensions.types import (
    CompactOptions,
    ContextUsage,
    Extension,
    ExtensionActions,
    ExtensionAPI,
    ExtensionCommandContext,
    ExtensionCommandContextActions,
    ExtensionContext,
    ExtensionContextActions,
    ExtensionError,
    ExtensionFactory,
    ExtensionFlag,
    ExtensionMode,
    ExtensionRuntime,
    ExtensionShortcut,
    ExtensionUIContext,
    InputEventResult,
    LoadExtensionsResult,
    ProviderConfig,
    RegisteredCommand,
    RegisteredTool,
    ResolvedCommand,
    ResourcesDiscoverEvent,
    ResourcesDiscoverResult,
    SessionShutdownEvent,
    SessionStartEvent,
    ToolDefinition,
    UserBashEvent,
    UserBashEventResult,
    define_tool,
)
from pi_mono.coding_agent.core.slash_commands import SlashCommandInfo, SlashCommandSource
from pi_mono.coding_agent.core.source_info import SourceInfo

__all__ = [
    "CompactOptions",
    "ContextUsage",
    "Extension",
    "ExtensionActions",
    "ExtensionAPI",
    "ExtensionCommandContext",
    "ExtensionCommandContextActions",
    "ExtensionContext",
    "ExtensionContextActions",
    "ExtensionError",
    "ExtensionFactory",
    "ExtensionFlag",
    "ExtensionMode",
    "ExtensionRunner",
    "ExtensionRuntime",
    "ExtensionShortcut",
    "ExtensionUIContext",
    "InputEventResult",
    "LoadExtensionsResult",
    "ProviderConfig",
    "RegisteredCommand",
    "RegisteredTool",
    "ResolvedCommand",
    "ResourcesDiscoverEvent",
    "ResourcesDiscoverResult",
    "SessionShutdownEvent",
    "SessionStartEvent",
    "SlashCommandInfo",
    "SlashCommandSource",
    "SourceInfo",
    "ToolDefinition",
    "UserBashEvent",
    "UserBashEventResult",
    "collect_configured_extension_paths",
    "create_extension_runtime",
    "define_tool",
    "discover_and_load_extensions",
    "discover_extensions_in_dir",
    "emit_session_shutdown_event",
    "load_extension_from_factory",
    "load_extensions",
]
