// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const AMAZON_BEDROCK_MANTLE_OPENAI_RESPONSES_MODELS = {
	"openai.gpt-5.4": {
		id: "openai.gpt-5.4",
		name: "GPT-5.4",
		api: "amazon-bedrock-mantle-openai-responses",
		provider: "amazon-bedrock-mantle-openai-responses",
		baseUrl: "https://bedrock-mantle.us-east-2.api.aws/openai/v1",
		reasoning: true,
		thinkingLevelMap: {"xhigh":"xhigh","off":"none"},
		input: ["text", "image"],
		cost: {
			input: 2.75,
			output: 16.5,
			cacheRead: 0.275,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	} satisfies Model<"amazon-bedrock-mantle-openai-responses">,
	"openai.gpt-5.5": {
		id: "openai.gpt-5.5",
		name: "GPT-5.5",
		api: "amazon-bedrock-mantle-openai-responses",
		provider: "amazon-bedrock-mantle-openai-responses",
		baseUrl: "https://bedrock-mantle.us-east-2.api.aws/openai/v1",
		reasoning: true,
		thinkingLevelMap: {"xhigh":"xhigh","off":"none","minimal":null},
		input: ["text", "image"],
		cost: {
			input: 5.5,
			output: 33,
			cacheRead: 0.55,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	} satisfies Model<"amazon-bedrock-mantle-openai-responses">,
} as const;
