import { openAICompletionsApi } from "../api/openai-completions.lazy.ts";
import { envApiKeyAuth } from "../auth/helpers.ts";
import { createProvider, type Provider } from "../models.ts";
import type { Model } from "../types.ts";

function apiarioModels(): Model<"openai-completions">[] {
	return [
		// ─── DeepSeek ───────────────────────────────────────────────────
		{
			id: "deepseek/deepseek-v4-flash",
			name: "DeepSeek v4 Flash",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: false,
			input: ["text"],
			cost: { input: 0.14, output: 0.27, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 384_000,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "deepseek/deepseek-v4-pro",
			name: "DeepSeek v4 Pro",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.41, output: 0.82, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 384_000,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},

		// ─── OpenAI ────────────────────────────────────────────────────
		{
			id: "openai/gpt-5.4",
			name: "GPT-5.4",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2.34, output: 14.01, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},
		{
			id: "openai/gpt-5.4-mini",
			name: "GPT-5.4 Mini",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 0.73, output: 4.19, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 400_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},
		{
			id: "openai/gpt-5.5",
			name: "GPT-5.5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 4.73, output: 28.03, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},
		{
			id: "openai/gpt-5.6-luna",
			name: "GPT-5.6 Luna",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 0.94, output: 5.6, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_050_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},
		{
			id: "openai/gpt-5.6-sol",
			name: "GPT-5.6 Sol",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 4.73, output: 28.03, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_050_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},
		{
			id: "openai/gpt-5.6-terra",
			name: "GPT-5.6 Terra",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2.36, output: 14.02, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_050_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},
		{
			id: "openai/o4-mini",
			name: "o4-mini",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1.04, output: 4.1, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 200_000,
			maxTokens: 16_384,
			compat: { supportsStore: false },
		},

		// ─── Anthropic ──────────────────────────────────────────────────
		{
			id: "anthropic/claude-haiku-4.5",
			name: "Claude Haiku 4.5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 0.94, output: 4.66, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 200_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-opus-4.1",
			name: "Claude Opus 4.1",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 13.75, output: 68.73, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 200_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-opus-4.5",
			name: "Claude Opus 4.5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 4.65, output: 23.27, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 200_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-opus-4.6",
			name: "Claude Opus 4.6",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 4.65, output: 23.27, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-opus-4.7",
			name: "Claude Opus 4.7",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 4.65, output: 23.27, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-opus-4.8",
			name: "Claude Opus 4.8",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 4.65, output: 23.27, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-sonnet-4.5",
			name: "Claude Sonnet 4.5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 2.8, output: 13.77, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 200_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-sonnet-4.6",
			name: "Claude Sonnet 4.6",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2.8, output: 13.95, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/claude-sonnet-5",
			name: "Claude Sonnet 5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2.81, output: 13.95, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/fable-5",
			name: "Claude Fable 5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 9.48, output: 47.12, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "anthropic/mythos-5",
			name: "Claude Mythos 5",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 9.48, output: 47.12, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 1_000_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},

		// ─── Maritaca ──────────────────────────────────────────────────
		{
			id: "maritaca/sabia-3.1",
			name: "Sabiá 3.1",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: false,
			input: ["text"],
			cost: { input: 0.91, output: 2.73, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 128_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "maritaca/sabia-4",
			name: "Sabiá 4",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: false,
			input: ["text"],
			cost: { input: 1.03, output: 3.75, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 128_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "maritaca/sabia-4-small",
			name: "Sabiá 4 Small",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: false,
			input: ["text"],
			cost: { input: 0.23, output: 0.82, cacheRead: 0, cacheWrite: 0 },
			contextWindow: 128_000,
			maxTokens: 8_192,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},

		// ─── Moonshot ──────────────────────────────────────────────────
		{
			id: "moonshot/kimi-k2.7-code",
			name: "Kimi K2.7 Code",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.88, output: 3.72, cacheRead: 0.18, cacheWrite: 0 },
			contextWindow: 262_144,
			maxTokens: 16_384,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
		{
			id: "moonshot/kimi-k3",
			name: "Kimi K3",
			api: "openai-completions",
			provider: "apiario",
			baseUrl: "https://api.apiario.dev/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2.79, output: 13.94, cacheRead: 0.28, cacheWrite: 0 },
			contextWindow: 1_048_576,
			maxTokens: 16_384,
			compat: { supportsStore: false, supportsDeveloperRole: false },
		},
	];
}

export function apiarioProvider(): Provider<"openai-completions"> {
	return createProvider({
		id: "apiario",
		name: "Apiário",
		baseUrl: "https://api.apiario.dev/v1",
		auth: { apiKey: envApiKeyAuth("Apiário API key", ["APIARIO_API_KEY"]) },
		models: apiarioModels(),
		api: openAICompletionsApi(),
	});
}
