// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/ark-coding-plan-cn.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const ARK_CODING_PLAN_CN_MODELS: ModelCatalog<typeof values, "ark-coding-plan-cn"> =
	flattenModelCatalog("ark-coding-plan-cn", values);
