// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/ark-agent-plan-cn.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const ARK_AGENT_PLAN_CN_MODELS: ModelCatalog<typeof values, "ark-agent-plan-cn"> =
	flattenModelCatalog("ark-agent-plan-cn", values);
