// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cline-pass.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const CLINE_PASS_MODELS: ModelCatalog<typeof values, "cline-pass"> =
	flattenModelCatalog("cline-pass", values);
