// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const DOUBAO_MODELS = {
        "doubao": {
                id: "doubao",
                name: "Doubao (ARK_MODEL_ID)",
                api: "openai-completions",
                provider: "doubao",
                baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
                compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens","supportsStrictMode":false,"supportsLongCacheRetention":false},
                reasoning: false,
                input: ["text"],
                cost: {
                        input: 0,
                        output: 0,
                        cacheRead: 0,
                        cacheWrite: 0,
                },
                contextWindow: 128000,
                maxTokens: 16000,
        } satisfies Model<"openai-completions">,
} as const;
