// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/llmgateway.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const LLMGATEWAY_MODELS: ChatModelCatalog<typeof values, "llmgateway"> =
	flattenChatModelCatalog("llmgateway", values);

export const LLMGATEWAY_IMAGE_MODELS: ImageModelCatalog<typeof values, "llmgateway"> =
	flattenImageModelCatalog("llmgateway", values);

export const LLMGATEWAY_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "llmgateway"> =
	flattenClassifierModelCatalog("llmgateway", values);
