// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/llmgateway.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const LLMGATEWAY_MODELS: ModelCatalog<typeof values, "llmgateway"> =
	flattenModelCatalog("llmgateway", values);
