// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/llmgateway-devpass.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const LLMGATEWAY_DEVPASS_MODELS: ModelCatalog<typeof values, "llmgateway-devpass"> =
	flattenModelCatalog("llmgateway-devpass", values);
