// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/llmgateway-devpass.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const LLMGATEWAY_DEVPASS_MODELS: ChatModelCatalog<typeof values, "llmgateway-devpass"> =
	flattenChatModelCatalog("llmgateway-devpass", values);

export const LLMGATEWAY_DEVPASS_IMAGE_MODELS: ImageModelCatalog<typeof values, "llmgateway-devpass"> =
	flattenImageModelCatalog("llmgateway-devpass", values);

export const LLMGATEWAY_DEVPASS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "llmgateway-devpass"> =
	flattenClassifierModelCatalog("llmgateway-devpass", values);
