// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/sheng-suan-yun.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const SHENG_SUAN_YUN_MODELS: ModelCatalog<typeof values, "sheng-suan-yun"> =
	flattenModelCatalog("sheng-suan-yun", values);
