// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/stepfun-ai.json" with { type: "json" };
import type { Model } from "../types.ts";

export const STEPFUN_AI_MODELS = values as {
	"step-3.5-flash": Model<"openai-completions"> & {
		id: "step-3.5-flash";
		provider: "stepfun-ai";
	};
	"step-3.5-flash-2603": Model<"openai-completions"> & {
		id: "step-3.5-flash-2603";
		provider: "stepfun-ai";
	};
	"step-3.7-flash": Model<"openai-completions"> & {
		id: "step-3.7-flash";
		provider: "stepfun-ai";
	};
};
