// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const TELNYX_MODELS = {
	"MiniMaxAI/MiniMax-M3-MXFP8": {
		id: "MiniMaxAI/MiniMax-M3-MXFP8",
		name: "MiniMax M3 MXFP8 (Telnyx)",
		api: "openai-completions",
		provider: "telnyx",
		baseUrl: "https://api.telnyx.com/v2/ai",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens","supportsStrictMode":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.27,
			output: 1.1,
			cacheRead: 0.08,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 262144,
	} satisfies Model<"openai-completions">,
	"moonshotai/Kimi-K2.6": {
		id: "moonshotai/Kimi-K2.6",
		name: "Kimi K2.6 (Telnyx)",
		api: "openai-completions",
		provider: "telnyx",
		baseUrl: "https://api.telnyx.com/v2/ai",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens","supportsStrictMode":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.665,
			output: 4,
			cacheRead: 0.08,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 262144,
	} satisfies Model<"openai-completions">,
	"zai-org/GLM-5.2": {
		id: "zai-org/GLM-5.2",
		name: "GLM 5.2 (Telnyx)",
		api: "openai-completions",
		provider: "telnyx",
		baseUrl: "https://api.telnyx.com/v2/ai",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens","supportsStrictMode":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1,
			output: 4,
			cacheRead: 0.2,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
	} satisfies Model<"openai-completions">,
} as const;
