// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/upstage.json" with { type: "json" };
import type { Model } from "../types.ts";

export const UPSTAGE_MODELS = values as {
	"solar-mini": Model<"openai-completions"> & {
		id: "solar-mini";
		provider: "upstage";
	};
	"solar-open2": Model<"openai-completions"> & {
		id: "solar-open2";
		provider: "upstage";
	};
	"solar-pro2": Model<"openai-completions"> & {
		id: "solar-pro2";
		provider: "upstage";
	};
	"solar-pro3": Model<"openai-completions"> & {
		id: "solar-pro3";
		provider: "upstage";
	};
};
