// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/volcengine-ark-coding.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const VOLCENGINE_ARK_CODING_MODELS: ModelCatalog<typeof values, "volcengine-ark-coding"> =
	flattenModelCatalog("volcengine-ark-coding", values);
