// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/yolo-auto.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const YOLO_AUTO_MODELS: ModelCatalog<typeof values, "yolo-auto"> =
	flattenModelCatalog("yolo-auto", values);
